services:
  migrate:
    deploy: { resources: { limits: { memory: 256M } } }
    memswap_limit: 256M
  api:
    deploy: { resources: { limits: { memory: 256M } } }
    memswap_limit: 256M
  event-consumer:
    deploy: { resources: { limits: { memory: 256M } } }
    memswap_limit: 256M
  scheduler:
    deploy: { resources: { limits: { memory: 128M } } }
    memswap_limit: 128M
  postgres:
    deploy: { resources: { limits: { memory: 384M } } }
    memswap_limit: 384M
  redpanda:
    deploy: { resources: { limits: { memory: 1G } } }
    memswap_limit: 1G
  redis:
    deploy: { resources: { limits: { memory: 64M } } }
    memswap_limit: 64M
