services:
  postgres:
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"
  redpanda:
    ports:
      - "127.0.0.1:${REDPANDA_PORT:-19092}:19092"
  redis:
    ports:
      - "127.0.0.1:${REDIS_PORT:-6379}:6379"
